name: Pytest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  seed-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Test
        run: python3 testing-seed.py
  wrapper-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Test
        run: python3 testing-wrapper.py